export const paths = {
  login: '/login',
  adminLogin: '/admin/login',
  signup: '/signup',
  home: '/home',
  simulation: '/simulation',
  reportApplication: '/report-application',
  reportStatus: '/report-status',
  reportDetail: '/report-status/detail/:id',
  legalityCheck: '/legality-check',
  review: '/review',
  regulatorOverview: '/regulator',
  regulatorIncomingReports: '/regulator/incoming-reports',
  regulatorRegisteredLoans: '/regulator/registered-loans',
  regulatorContent: '/regulator/content',
  regulatorSettings: '/regulator/settings',
  regulatorSuperAdmin: '/regulator/super-admin',
  education: '/education',
  articleDetail: '/education/article/:slugOrId',
} as const
